spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.0.132.17:3306/morandi
    username: root
    password: Pepsi1943@

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  doc:
    packages-to-scan: com.test.demo
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /api-docs/json
    cache:
      disabled: true

oauth:
  google:
    client-id: "1047762864117-c4i1inqqugoesvruk7gkjv0itdnm9mov.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: http://3.38.152.28:8080/oauths/github/callback

  github:
    client-id: "202fee18f40f0edd7e64"
    client-secret: "8bd777f3df672d764b51051e658d829e41d23d37"
    redirect-uri: http://3.38.152.28:8080/oauths/google/callback
