spring:
  profiles:
    active: SERVICE

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1/morandi
    username: root
    password: 1234

  redis:
    host: 127.0.0.1
    port: 6379


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  doc:
    packages-to-scan: com.test.demo
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /api-docs/json
    cache:
      disabled: true


oauth:
  google:
    client-id: "1047762864117-c4i1inqqugoesvruk7gkjv0itdnm9mov.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: http://localhost:8080/oauths/google/callback

  github:
    client-id: "202fee18f40f0edd7e64"
    client-secret: "8bd777f3df672d764b51051e658d829e41d23d37"
    redirect-uri: http://localhost:8080/oauths/github/callback

sentry:
  dsn: https://2ea46680d1a6e8dd5eb34ed97d3cdf64@o4505639286145024.ingest.sentry.io/4505639321862144
  traces-sample-rate: 1.0
